id: P5BB19136
initial_creation_type: input
source_metadata:
  title: Paramārthasāra with Yogarāja's Paramārthasārasaṃgrahavivṛti commentary
  language:
  - English
  - Sanskrit
  term: Sanskrit -- Śāstra -- Philosophy -- Śaiva
  data entry: Lyne Bansat-Boudon
  contribution to GRETIL: Lyne Bansat-Boudon
  initial normalization and conversion to legacy GRETIL formats: Reinhold Grünendahl
  normalization and conversion to TEI-conformant markup: Maximilian Mehner
created_at: '2022-03-09T15:05:40.902828'
last_modified_at: '2022-03-09T15:05:40.902841'
